export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';

export const FETCH_USER_POSTS_PENDING = 'FETCH_USER_POSTS_PENDING';
export const FETCH_USER_POSTS_FULFILLED = 'FETCH_USER_POSTS_FULFILLED';
export const FETCH_USER_POSTS_REJECTED = 'FETCH_USER_POSTS_REJECTED';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_CANCEL = 'EDIT_USER_CANCEL';

export const SAVE_USER_PENDING = 'UPDATE_USER_PENDING';
export const SAVE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';
export const SAVE_USER_REJECTED = 'UPDATE_USER_REJECTED';

export const UPDATE_USER_FIELD = 'UPDATE_USER_FIELD';
